=== 1677030156NguyenMinhPhuongKHMT17-01/DichVuKetNoiVaCongNgheNenTang_1677030156/03_Postman/queue-contract-tests/pair-04-core-notification/schema/alert.created.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "event_id", 
      "event_name", 
      "alert_id", 
      "severity", 
      "message", 
      "timestamp", 
      "correlationId", 
      "source"
    ],
    "properties": {
      "event_id": { "type": "string", "format": "uuid" },
      "event_name": { "const": "alert.created" },
      "correlationId": { "type": "string", "format": "uuid" },
      "source": { "const": "core-business" },
      "alert_id": { "type": "string", "minLength": 3 },
      "severity": { "enum": ["low", "medium", "high", "critical"] },
      "message": { "type": "string", "minLength": 5 },
      "target_channels": {
        "type": "array",
        "items": { 
          "type": "string", 
          "enum": ["telegram", "email", "discord", "sms"] 
        }
      },
      "timestamp": { "type": "string", "format": "date-time" }
    }
  }

=== 1677030156NguyenMinhPhuongKHMT17-01/DichVuKetNoiVaCongNgheNenTang_1677030156/03_Postman/queue-contract-tests/pair-04-core-notification/samples/valid/alert-created-valid-standard.json
{
    "event_id": "123e4567-e89b-12d3-a456-426614174000",
    "event_name": "alert.created",
    "correlationId": "0196fb3d-4ad7-7d1e-9f49-5d5148d2babc",
    "source": "core-business",
    "alert_id": "ALT-2026-001",
    "severity": "high",
    "message": "Phát hiện truy cập trái phép tại cổng chính",
    "target_channels": [
      "telegram",
      "email"
    ],
    "timestamp": "2026-08-13T08:35:00+07:00"
  }

=== 1677030156NguyenMinhPhuongKHMT17-01/DichVuKetNoiVaCongNgheNenTang_1677030156/03_Postman/queue-contract-tests/pair-04-core-notification/samples/valid/alert-created-valid-boundary.json
{
    "event_id": "123e4567-e89b-12d3-a456-426614174001",
    "event_name": "alert.created",
    "correlationId": "0196fb3d-4ad7-7d1e-9f49-5d5148d2babd",
    "source": "core-business",
    "alert_id": "ALT-2026-002",
    "severity": "low",
    "message": "Nhiệt độ phòng vượt ngưỡng cảnh báo nhẹ",
    "timestamp": "2026-08-13T08:40:00+07:00"
  }
